issue of liner.vue fixed
xaankoow/segmento-nuxt pull request #140
Opened 2023-09-24 14:47 UTC by farzad2919

### Request type :question:

- [ ] :bug: Bug ( fixed or found bug )
- [ ] :new: New feature ( make new feature or add some things new in project )
- [ ] :star2: Config ( change config files or install )
- [ ] :rocket: Performance ( when you do something that can improve performance )
- [ ] :books: Document ( when code has documentation or document change )
- [ ] ✏️ Update (when some lines have to get updates, no bug, no new feature!)

### Description :books:

- What did you do

### How to use ⚒️

- What is necessary to do

2023-09-24 14:51 UTC, farzad2919 commented
issue of "liner.vue" component fixed , but i did not use this component in new page.

2023-09-26 17:26 UTC, farzad2919 commented
سلام.عذر میخوام دیر شد سیستمم به مشکل خورده هنوز نتونستم اصلاحات رو انجام
بدم.همچنان درگیر درست کردن سیستم هستم

On Tue, Sep 26, 2023, 6:21 PM Babak Majd ***@***.***> wrote:

> Reopened #140 <https://github.com/xaankoow/segmento-nuxt/pull/140>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/xaankoow/segmento-nuxt/pull/140#event-10476384298>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYGGYSTROCIB3PMC4UBO7LLX4LTXZANCNFSM6AAAAAA5E7RIW4>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2023-10-01 16:15 UTC, babak-x commented on components/Input/Text/Area/Liner.vue
> +    textAreaDiv.value.style.height = "1000px";
Seriously?

![image](https://github.com/xaankoow/segmento-nuxt/assets/118653430/70d626d8-10d5-44ab-bb4c-8444344b38e0)

2023-10-01 16:31 UTC, babak-x requested changes
Actualy, you didn't fix it! You hide it.

2023-10-01 16:31 UTC, closed without merging